-- Typed models for the Postcodesio SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Nearest
---@field result table
---@field status number

---@class NearestListMatch
---@field postcode_id string

---@class Outcode
---@field id? string

---@class OutcodeLoadMatch
---@field id string

---@class Place
---@field code string
---@field country string
---@field county_unitary string
---@field county_unitary_type string
---@field district_borough string
---@field district_borough_type? string
---@field eastings number
---@field id? string
---@field latitude number
---@field local_type string
---@field longitude number
---@field max_eastings number
---@field max_northings number
---@field min_eastings number
---@field min_northings number
---@field name_1 string
---@field name_1_lang string
---@field name_2 string
---@field name_2_lang string
---@field northings number
---@field outcode string
---@field region string

---@class PlaceLoadMatch
---@field id string

---@class PlaceListMatch
---@field code? string
---@field country? string
---@field county_unitary? string
---@field county_unitary_type? string
---@field district_borough? string
---@field district_borough_type? string
---@field eastings? number
---@field id? string
---@field latitude? number
---@field local_type? string
---@field longitude? number
---@field max_eastings? number
---@field max_northings? number
---@field min_eastings? number
---@field min_northings? number
---@field name_1? string
---@field name_1_lang? string
---@field name_2? string
---@field name_2_lang? string
---@field northings? number
---@field outcode? string
---@field region? string

---@class Postcode
---@field admin_county string
---@field admin_district string
---@field admin_ward string
---@field bua? string
---@field cancer_alliance? string
---@field ccg string
---@field ced string
---@field codes table
---@field country string
---@field date_of_introduction? string
---@field eastings number
---@field european_electoral_region string
---@field icb? string
---@field id? string
---@field incode string
---@field latitude number
---@field lep1? string
---@field lep2? string
---@field longitude number
---@field lsoa string
---@field lsoa11? string
---@field lsoa21? string
---@field msoa string
---@field msoa11? string
---@field msoa21? string
---@field national_park? string
---@field nhs_ha string
---@field nhs_region? string
---@field northings number
---@field nuts string
---@field oa21? string
---@field outcode string
---@field parish string
---@field parliamentary_constituency string
---@field parliamentary_constituency_2024? string
---@field pfa? string
---@field postcode string
---@field primary_care_trust string
---@field quality number
---@field region string
---@field result table
---@field ruc11? string
---@field ruc21? string
---@field status number
---@field ttwa? string

---@class PostcodeLoadMatch
---@field id string

---@class PostcodeListMatch
---@field filter? string
---@field latitude? number
---@field limit? number
---@field longitude? number
---@field query? any
---@field radius? number
---@field widesearch? boolean

---@class PostcodeCreateData
---@field admin_county string
---@field admin_district string
---@field admin_ward string
---@field bua? string
---@field cancer_alliance? string
---@field ccg string
---@field ced string
---@field codes table
---@field country string
---@field date_of_introduction? string
---@field eastings number
---@field european_electoral_region string
---@field icb? string
---@field id? string
---@field incode string
---@field latitude number
---@field lep1? string
---@field lep2? string
---@field longitude number
---@field lsoa string
---@field lsoa11? string
---@field lsoa21? string
---@field msoa string
---@field msoa11? string
---@field msoa21? string
---@field national_park? string
---@field nhs_ha string
---@field nhs_region? string
---@field northings number
---@field nuts string
---@field oa21? string
---@field outcode string
---@field parish string
---@field parliamentary_constituency string
---@field parliamentary_constituency_2024? string
---@field pfa? string
---@field postcode string
---@field primary_care_trust string
---@field quality number
---@field region string
---@field result table
---@field ruc11? string
---@field ruc21? string
---@field status number
---@field ttwa? string

---@class ScottishPostcode
---@field id? string
---@field result table
---@field status number

---@class ScottishPostcodeLoadMatch
---@field id string

---@class TerminatedPostcode
---@field id? string
---@field result table
---@field status number

---@class TerminatedPostcodeLoadMatch
---@field id string

local M = {}

return M
